skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
gateway_deposit = "MCFeMZJYARXVcLvuFbajFC8BzHZNS6Ef8DV59RiteL1"

[programs.localnet]
gateway_deposit = "MCFeMZJYARXVcLvuFbajFC8BzHZNS6Ef8DV59RiteL1"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-node tests/gateway-deposit.ts"

[hooks]
